chore(ci): standardize workflows

diff --git a/.github/workflows/build-nocgo.yml b/.github/workflows/build-nocgo.yml
--- a/.github/workflows/build-nocgo.yml
+++ b/.github/workflows/build-nocgo.yml
@@ -7,27 +7,27 @@ on: # yamllint disable-line rule:truthy
   workflow_call: # Required so this workflow can be called from another workflow
     inputs:
       cgo_enabled:
-        default: "0"
+        default: '0'
         type: string # required
       goarches:
         default: default
         type: string # required
       test_opts:
-        default: "-v"
+        default: '-v'
         type: string # required
   workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
     inputs:
       # checkov:skip=CKV_GHA_7:The build output cannot be affected by user parameters...
       cgo_enabled:
-        description: "CGO_ENABLED"
+        description: 'CGO_ENABLED'
         type: choice
-        default: "0"
+        default: '0'
         options:
-          - "0"
-          - "1"
+          - '0'
+          - '1'
       # checkov:skip=CKV_GHA_7:The build output cannot be affected by user parameters...
       goarches:
-        description: "Build on the default GOARCH, or all GOARCHes for the OS"
+        description: 'Build on the default GOARCH, or all GOARCHes for the OS'
         type: choice
         options:
           - default
@@ -35,63 +35,70 @@ on: # yamllint disable-line rule:truthy
         default: default
        # checkov:skip=CKV_GHA_7: The build output cannot be affected by user parameters...
       test_opts:
-        description: "Test options (eg: -v -run TestX -short -tags debug)"
+        description: 'Test options (eg: -v -run TestX -short -tags debug)'
         type: string
-        default: "-v"
+        default: '-v'
 
 env:
   CGO_ENABLED: ${{ inputs.cgo_enabled }}
-  goarches: ${{ inputs.goarches }}
+  GOARCHES: ${{ inputs.goarches }}
   TEST_OPTS: ${{ inputs.test_opts }}
 
 jobs:
   build-nocgo:
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v7
+      - uses: actions/checkout@v7
+        with:
+          fetch-depth: 1
+          show-progress: false
 
-    - uses: actions/setup-go@v7
-      with:
-        go-version: '1.26'
-        check-latest: true
+      - uses: actions/setup-go@v7
+        with:
+          go-version-file: go.mod
+          check-latest: true
+          cache: true
 
-    - run: printf '::notice ::%s\n' "$(go version)"
+      - run: printf '::notice ::%s\n' "$(go version)"
 
-    - name: go build (all targets but android and ios)
-      run: |
-        # go build (all targets but android and ios)
-        : "${goarches:=all}"
-        printf 'CGO_ENABLED=%s\n' "${CGO_ENABLED:-}"
-        printf 'goarches=%s\n' "${goarches:-}"
-        mapfile -t targets < <(go tool dist list | grep -E -v '(android|ios)')
-        set +e
-        fails=0
-        builds=0
-        declare -A seen
-        for target in "${targets[@]}"; do
-          export GOOS="${target%%/*}"
-          if [[ -v seen["${GOOS}"] ]]; then
-            if [[ "${goarches}" != "all" ]]; then
-              continue
+      - name: go build (all targets but android and ios)
+        run: |
+          # go build (all targets but android and ios)
+          : "${GOARCHES:=all}"
+          printf 'CGO_ENABLED=%s\n' "${CGO_ENABLED:-}"
+          printf 'GOARCHES=%s\n' "${GOARCHES}"
+          mapfile -t targets < <(go tool dist list | grep -E -v '(android|ios)')
+          set +e
+          fails=0
+          builds=0
+          declare -A seen
+          for target in "${targets[@]}"; do
+            export GOOS="${target%%/*}"
+            if [[ -v seen["${GOOS}"] ]]; then
+              if [[ "${GOARCHES}" != "all" ]]; then
+                continue
+              fi
             fi
+            export GOARCH="${target#*/}"
+            echo "Build ${builds}: ${target}"
+            if ! go build -trimpath .; then
+              echo "::warning ::Failed to build ${target}"
+              ((fails++))
+            fi
+            seen["${GOOS}"]=1
+            ((builds++))
+          done
+          if ((fails>0)); then
+            echo "::warning ::${fails} of ${builds} builds failed"
           fi
-          export GOARCH="${target#*/}"
-          echo "Build ${builds}: ${target}"
-          if ! go build -trimpath .; then
-            echo "::warning ::Failed to build ${target}"
-            ((fails++))
-          fi
-          seen["${GOOS}"]=1
-          ((builds++))
-        done
-        if ((fails>0)); then
-          echo "::warning ::${fails} of ${builds} builds failed"
-        fi
-        exit "${fails}"
+          exit "${fails}"
 
-    - name: go test .
-      run: |
-        # go test ${TEST_OPTS} .
-        : "${TEST_OPTS:=}"
-        go test ${TEST_OPTS} .
+      - name: go test .
+        run: |
+          # go test ${TEST_OPTS} .
+          : "${TEST_OPTS:=}"
+          go test ${TEST_OPTS} .
+
+permissions:
+  contents: read
diff --git a/.github/workflows/test-netbsd.yml b/.github/workflows/test-netbsd.yml
--- a/.github/workflows/test-netbsd.yml
+++ b/.github/workflows/test-netbsd.yml
@@ -3,74 +3,75 @@
 
 name: test-netbsd
 
-on:
+on: # yamllint disable-line rule:truthy
   workflow_call:
   workflow_dispatch:
 
-permissions:
-  contents: read
+env:
+  CODECOV_SLUG: ${{ github.repository }}
+  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+  GOOS: netbsd
+  GOARCH: amd64
 
 jobs:
   test-netbsd:
     name: test-netbsd
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
     timeout-minutes: 20
-    env:
-      GOOS: netbsd
-      GOARCH: amd64
-      CODECOV_SLUG: ${{ github.repository }}
-      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
     # continue-on-error: true
     steps:
-    - uses: actions/checkout@v7
-      with:
-        show-progress: false
+      - uses: actions/checkout@v7
+        with:
+          fetch-depth: 1
+          show-progress: false
 
-    - uses: vmactions/netbsd-vm@v1
-      with:
-        envs: 'GOOS GOARCH CODECOV_SLUG CODECOV_TOKEN' # GITHUB_TOKEN'
-        usesh: true
-        # copyback: false
-        # See https://github.com/fsnotify/fsnotify/blob/main/.github/workflows/test.yml
-        # default PATH:
-        # /usr/bin
-        # /bin
-        # /usr/pkg/bin
-        # /usr/local/bin
-        prepare: |
-          export PATH="/usr/sbin:${PATH}"
-          tries=9
-          left="${tries}"
-          delay=1
-          while true; do
-            pkg_add bash coreutils curl git gzip gtar jq || true
-            if which curl git gzip gtar gsha256sum jq; then
-              echo All dependencies have been installed
-              break
-            fi
-            echo One or more dependencies have not yet been installed
-            left=$((left - 1))
-            if [ "${left}" -le 0 ]; then
-              printf 'FAIL: pkg_add failed all %s attempts\n' "${tries}"
-              exit 1
-            fi
-            tried=$((tries - left + 1))
-            printf 'Attempting %s of %s tries in %s seconds...\n' "${tried}" "${tries}" "${delay}"
-            sleep "${delay}"
-            delay=$((delay * 2))
-          done
-          cd /usr/pkg/bin && ln -sf gsha256sum sha256sum
-          # pkg_add go
-        # if we are using: pkg_add go
-        # (cd /usr/pkg/bin ; ln -sf go??? go)
-        # ls -l /usr/pkg/bin
-        run: |
-          ./download-build-test.sh
+      - uses: vmactions/netbsd-vm@v1
+        with:
+          envs: 'GOOS GOARCH CODECOV_SLUG CODECOV_TOKEN' # GITHUB_TOKEN'
+          usesh: true
+          # copyback: false
+          # See https://github.com/fsnotify/fsnotify/blob/main/.github/workflows/test.yml
+          # default PATH:
+          # /usr/bin
+          # /bin
+          # /usr/pkg/bin
+          # /usr/local/bin
+          prepare: |
+            export PATH="/usr/sbin:${PATH}"
+            tries=9
+            left="${tries}"
+            delay=1
+            while true; do
+              pkg_add bash coreutils curl git gzip gtar jq || true
+              if which curl git gzip gtar gsha256sum jq; then
+                echo All dependencies have been installed
+                break
+              fi
+              echo One or more dependencies have not yet been installed
+              left=$((left - 1))
+              if [ "${left}" -le 0 ]; then
+                printf 'FAIL: pkg_add failed all %s attempts\n' "${tries}"
+                exit 1
+              fi
+              tried=$((tries - left + 1))
+              printf 'Attempting %s of %s tries in %s seconds...\n' "${tried}" "${tries}" "${delay}"
+              sleep "${delay}"
+              delay=$((delay * 2))
+            done
+            cd /usr/pkg/bin && ln -sf gsha256sum sha256sum
+            # pkg_add go
+          # if we are using: pkg_add go
+          # (cd /usr/pkg/bin ; ln -sf go??? go)
+          # ls -l /usr/pkg/bin
+          run: |
+            ./download-build-test.sh
 
-    - uses: codecov/codecov-action@v7
-      with:
-        # fail_ci_if_error: false
-        files: ./coverage.out
-        name: coverage-${{ env.GOOS }}
-        token: ${{ secrets.CODECOV_TOKEN }}
+      - uses: codecov/codecov-action@v7
+        with:
+          # fail_ci_if_error: false
+          files: ./coverage.out
+          name: coverage-${{ env.GOOS }}
+          token: ${{ secrets.CODECOV_TOKEN }}
+
+permissions:
+  contents: read
diff --git a/.github/workflows/test-solaris.yml b/.github/workflows/test-solaris.yml
--- a/.github/workflows/test-solaris.yml
+++ b/.github/workflows/test-solaris.yml
@@ -3,53 +3,54 @@
 
 name: test-solaris
 
-on:
+on: # yamllint disable-line rule:truthy
   workflow_call:
   workflow_dispatch:
 
-permissions:
-  contents: read
+env:
+  CODECOV_SLUG: ${{ github.repository }}
+  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+  GOOS: solaris
+  GOARCH: amd64
 
 jobs:
   test-solaris:
     name: test-solaris
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
     timeout-minutes: 20
-    env:
-      GOOS: solaris
-      GOARCH: amd64
-      CODECOV_SLUG: ${{ github.repository }}
-      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-      # GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
     # continue-on-error: true
     steps:
-    - uses: actions/checkout@v7
-      with:
-        show-progress: false
+      - uses: actions/checkout@v7
+        with:
+          fetch-depth: 1
+          show-progress: false
 
-    - uses: vmactions/solaris-vm@v1
-      with:
-        envs: 'GOOS GOARCH CODECOV_SLUG CODECOV_TOKEN' # GITHUB_TOKEN'
-        usesh: true
-        # copyback: false
-        prepare: |
-          set +e
-          # ignore error 4, which is returned when there's nothing to do
-          # See https://github.com/vmactions/solaris-builder/blob/cda522c7/hooks/postBuild.sh#L55
-          pkg refresh --full
-          pkg install --accept shell/bash || true
-          pkg install --accept web/curl || true
-          pkg install --accept developer/versioning/git || true
-          pkg install --accept archiver/gnu-tar || true
-          pkg install --accept compress/gzip || true
-          pkg install --accept text/jq || true
-          # pkg install --accept developer/go || true
-        run: |
-          ./download-build-test.sh
+      - uses: vmactions/solaris-vm@v1
+        with:
+          envs: 'GOOS GOARCH CODECOV_SLUG CODECOV_TOKEN' # GITHUB_TOKEN'
+          usesh: true
+          # copyback: false
+          prepare: |
+            set +e
+            # ignore error 4, which is returned when there's nothing to do
+            # See https://github.com/vmactions/solaris-builder/blob/cda522c7/hooks/postBuild.sh#L55
+            pkg refresh --full
+            pkg install --accept shell/bash || true
+            pkg install --accept web/curl || true
+            pkg install --accept developer/versioning/git || true
+            pkg install --accept archiver/gnu-tar || true
+            pkg install --accept compress/gzip || true
+            pkg install --accept text/jq || true
+            # pkg install --accept developer/go || true
+          run: |
+            ./download-build-test.sh
 
-    - uses: codecov/codecov-action@v7
-      with:
-        # fail_ci_if_error: false
-        files: ./coverage.out
-        name: coverage-${{ env.GOOS }}
-        token: ${{ secrets.CODECOV_TOKEN }}
+      - uses: codecov/codecov-action@v7
+        with:
+          # fail_ci_if_error: false
+          files: ./coverage.out
+          name: coverage-${{ env.GOOS }}
+          token: ${{ secrets.CODECOV_TOKEN }}
+
+permissions:
+  contents: read
