fix(ci): add annotations to test-freebsd.yml

diff --git a/.github/workflows/test-freebsd.yml b/.github/workflows/test-freebsd.yml
--- a/.github/workflows/test-freebsd.yml
+++ b/.github/workflows/test-freebsd.yml
@@ -13,6 +13,7 @@ jobs:
     name: test-freebsd
     runs-on: ubuntu-latest
     timeout-minutes: 10
+    continue-on-error: true
     # env:
     #  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
     steps:
@@ -30,5 +31,11 @@ jobs:
         run: |
           printf '::notice ::%s\n' "$(go version)"
           go env
-          go build ./...
-          go test -v
+          if !.go build ./...; then
+            printf "::error ::go build failed: error %s\n" "$?"
+            exit 1
+          fi
+          if ! go test -v; then
+            printf '::error ::go test failed: error %s\n" "$?"
+            exit 1
+          fi
