fix(ci): clean up workflows

diff --git a/.github/workflows/test-freebsd.yml b/.github/workflows/test-freebsd.yml
--- a/.github/workflows/test-freebsd.yml
+++ b/.github/workflows/test-freebsd.yml
@@ -29,16 +29,19 @@ jobs:
           pkg update -f
           pkg install -y go
         run: |
-          # printf '::notice ::%s\n' "$(go version)"
-          go env
+          go version
+          rv=0
           if go build ./...; then
             echo "::notice ::build succeeded"
           else
-            echo "::error ::build failed"
+            rv=$?
+            printf '::error ::build failed: error %s\n" "${rv}"
           fi
           if go test -v ./...; then
             echo "::notice ::tests succeeded"
           else
-            echo '::error ::tests failed"
-            exit 1
+            rv=$?
+            printf '::error ::tests failed: error %s\n" "${rv}"
           fi
+          exit "${rv}"
+
diff --git a/.github/workflows/test-illumos.yml b/.github/workflows/test-illumos.yml
--- a/.github/workflows/test-illumos.yml
+++ b/.github/workflows/test-illumos.yml
@@ -31,18 +31,22 @@ jobs:
           pkg_version="${GO_VERSION//.}"
           pkg install "go-${pkg_version}"
         run: |
-          PATH="/opt/ooce/go-${{ env.GO_VERSION }}/bin:${PATH}"
+          GO_VERSION="${{ env.GO_VERSION }}"
+          PATH="/opt/ooce/go-${GO_VERSION}/bin:${PATH}"
           export PATH
-          # printf '::notice ::%s\n' "$(go version)"
-          go env
+          go version
+          rv=0
           if go build ./...; then
             echo "::notice ::build succeeded"
           else
-            echo "::error ::build failed"
+            rv=$?
+            printf '::error ::build failed: error %s\n" "${rv}"
           fi
           if go test -v ./...; then
             echo "::notice ::tests succeeded"
           else
-            echo '::error ::tests failed"
-            exit 1
+            rv=$?
+            printf '::error ::tests failed: error %s\n" "${rv}"
           fi
+          exit "${rv}"
+
diff --git a/.github/workflows/test-netbsd.yml b/.github/workflows/test-netbsd.yml
--- a/.github/workflows/test-netbsd.yml
+++ b/.github/workflows/test-netbsd.yml
@@ -22,7 +22,7 @@ jobs:
     - uses: vmactions/netbsd-vm@v1
       with:
         # envs: 'GITHUB_TOKEN'
-        # usesh: true
+        usesh: true
         # See https://github.com/fsnotify/fsnotify/blob/main/.github/workflows/test.yml
         prepare: |
           export PATH="/usr/pkg/bin:${PATH}"
@@ -38,18 +38,20 @@ jobs:
           done
 
         run: |
-            export PATH="/usr/pkg/bin:${PATH}"
-            (cd /usr/pkg/bin ; ln -sf go??? go)
-            # printf '::notice ::%s\n' "$(go version)"
-            go env
-            if go build ./...; then
-              echo "::notice ::build succeeded"
-            else
-              echo "::error ::build failed"
-            fi
-            if go test -v ./...; then
-              echo "::notice ::tests succeeded"
-            else
-              echo '::error ::tests failed"
-              exit 1
-            fi
+          export PATH="/usr/pkg/bin:${PATH}"
+          (cd /usr/pkg/bin ; ln -sf go??? go)
+          go version
+          rv=0
+          if go build ./...; then
+            echo "::notice ::build succeeded"
+          else
+            rv=$?
+            printf '::error ::build failed: error %s\n" "${rv}"
+          fi
+          if go test -v ./...; then
+            echo "::notice ::tests succeeded"
+          else
+            rv=$?
+            printf '::error ::tests failed: error %s\n" "${rv}"
+          fi
+          exit "${rv}"
