fix: test-netbsd tweaks

diff --git a/.github/workflows/test-netbsd.yml b/.github/workflows/test-netbsd.yml
--- a/.github/workflows/test-netbsd.yml
+++ b/.github/workflows/test-netbsd.yml
@@ -26,26 +26,19 @@ jobs:
         copyback: false
         # See https://github.com/fsnotify/fsnotify/blob/main/.github/workflows/test.yml
         prepare: |
-          PATH="/usr/pkg/sbin:${PATH}"
+          PATH="/usr/sbin:${PATH}"
           export PATH
           if ! command -v pkg_add; then
-            find / -name 'pkg_add' -type f 2>/dev/null
+            find / -name 'pkg_add' -type f 2>/dev/null || true
           fi
-          attempts=4
-          delay=1
-          i=1
-          while [ "${i}" -le "${attempts}" ]; do
-            pkg_add go && break
-            echo "Attempt ${i} failed. Retrying in ${delay} seconds..."
-            sleep "${delay}"
-            delay=$(expr "${delay}" \* 2)
-            i=$(expr "${i}" + 1)
-          done
+          pkg_add go
 
         run: |
           PATH="/usr/pkg/bin:${PATH}"
           export PATH
           (cd /usr/pkg/bin ; ln -sf go??? go)
+          ls -l /usr/pkg/bin
+          command -v go
 
           go version
           rv=0
@@ -62,3 +55,14 @@ jobs:
             printf '::error ::tests failed: %s (error %s)\n' "$(go version)" "${rv}"
           fi
           exit "${rv}"
+
+# attempts=4
+# delay=1
+# i=1
+# while [ "${i}" -le "${attempts}" ]; do
+#   pkg_add go && break
+#   echo "Attempt ${i} failed. Retrying in ${delay} seconds..."
+#   sleep "${delay}"
+#   delay=$(expr "${delay}" \* 2)
+#   i=$(expr "${i}" + 1)
+# done
